# Global settings applied to the whole site.
[build]
  publish = "public"
  command = "hugo --gc --minify"
  
[context.production.environment]
HUGO_VERSION = "0.54.0"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.46"


